version: '3.7'

services:
  server:
    build: 
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: prisma-graphql
    environment:
      - NODE_ENV=development
      - COMMAND=${COMMAND:-start:dev}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    env_file:
      - ${ENV_ROOT}
    volumes:
      - ./app:/app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    container_name: test-db
    ports: 
      - "${POSTGRES_HOST}:${POSTGRES_HOST}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ${ENV_ROOT}

volumes:
  postgres-data: